/// Distribution-owned field type, independent of Kubernetes generated models.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FieldType {
    Boolean,
    Integer,
    String,
    OptionalBool,
    StringList,
    StringMap,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FieldSpec {
    pub path: &'static str,
    pub kind: FieldType,
    pub owner: &'static str,
    pub secret: bool,
    pub immutable: bool,
}
/// All baseline registry fields. apiVersion/kind are separately owned schema metadata.
pub const FIELDS: &[FieldSpec] = &[
    FieldSpec {
        path: "api.enabled",
        kind: FieldType::Boolean,
        owner: "E23",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "api.socketPath",
        kind: FieldType::String,
        owner: "E23",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "d2k.enabled",
        kind: FieldType::Boolean,
        owner: "E20",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "d2k.namespace",
        kind: FieldType::String,
        owner: "E20",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "kubernetes.apiServer.extraSANs",
        kind: FieldType::StringList,
        owner: "E07/E10/E11/E13",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "kubernetes.apiServer.startupTimeoutSeconds",
        kind: FieldType::Integer,
        owner: "E07/E10/E11/E13",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "kubernetes.kubelet.cpuManager.policy",
        kind: FieldType::String,
        owner: "E07/E10/E11/E13",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "kubernetes.kubelet.cpuManager.policyOptions",
        kind: FieldType::StringMap,
        owner: "E07/E10/E11/E13",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "kubernetes.kubelet.cpuManager.reservedCPUs",
        kind: FieldType::String,
        owner: "E07/E10/E11/E13",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "kubernetes.kubelet.systemReserved",
        kind: FieldType::StringMap,
        owner: "E07/E10/E11/E13",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "kubernetes.nodeName",
        kind: FieldType::String,
        owner: "E07/E10/E11/E13",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "logging.debug",
        kind: FieldType::Boolean,
        owner: "E21",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "logging.pprof",
        kind: FieldType::Boolean,
        owner: "E21",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "metrics.bindAddress",
        kind: FieldType::String,
        owner: "E21",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "metrics.enabled",
        kind: FieldType::Boolean,
        owner: "E21",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "network.disableIPv6",
        kind: FieldType::Boolean,
        owner: "E15/E16",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "network.loadBalancer.enabled",
        kind: FieldType::Boolean,
        owner: "E15/E16",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "network.loadBalancer.ip",
        kind: FieldType::String,
        owner: "E15/E16",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "network.mtu",
        kind: FieldType::Integer,
        owner: "E15/E16",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "network.nodeIP",
        kind: FieldType::String,
        owner: "E15/E16",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "path",
        kind: FieldType::String,
        owner: "E03/E05",
        secret: false,
        immutable: true,
    },
    FieldSpec {
        path: "portainer.async",
        kind: FieldType::Boolean,
        owner: "E19",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "portainer.edgeID",
        kind: FieldType::String,
        owner: "E19",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "portainer.edgeKey",
        kind: FieldType::String,
        owner: "E19",
        secret: true,
        immutable: false,
    },
    FieldSpec {
        path: "portainer.image",
        kind: FieldType::String,
        owner: "E19",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "runtime.containerMode",
        kind: FieldType::OptionalBool,
        owner: "E09",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "runtime.endpoint",
        kind: FieldType::String,
        owner: "E09",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "storage.dbWALRepair",
        kind: FieldType::Boolean,
        owner: "E08/E18",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "storage.localPath.enabled",
        kind: FieldType::Boolean,
        owner: "E08/E18",
        secret: false,
        immutable: false,
    },
    FieldSpec {
        path: "storage.localPath.sharedPath",
        kind: FieldType::String,
        owner: "E08/E18",
        secret: false,
        immutable: false,
    },
];
