[package]
name = "rubix-kube"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
autotests = false

[lints]
workspace = true

[dependencies]
rubix-config = { version = "=0.1.0", path = "../rubix-config" }
rubix-network = { version = "=0.1.0", path = "../rubix-network" }
serde_json = "=1.0.151"
rubix-platform = { version = "=0.1.0", path = "../rubix-platform" }
rubix-supervisor = { version = "=0.1.0", path = "../rubix-supervisor" }
bytes = "=1.12.1"
http = "=1.5.0"
http-body-util = "=0.1.5"
hyper = { version = "=1.11.1", features = ["http1", "server"] }
hyper-util = { version = "=0.1.21", features = ["tokio", "server", "http1"] }
tokio = { version = "=1.53.1", features = ["rt", "rt-multi-thread", "sync", "time", "macros", "signal", "net", "io-util", "fs"] }

rubix-apiserver = { version = "=0.1.0", path = "../rubix-apiserver" }
rubix-containerd = { version = "=0.1.0", path = "../rubix-containerd" }
rubix-controller = { version = "=0.1.0", path = "../rubix-controller" }
rubix-cri = { version = "=0.1.0", path = "../rubix-cri" }
rubix-datastore = { version = "=0.1.0", path = "../rubix-datastore" }
rubix-dns = { version = "=0.1.0", path = "../rubix-dns" }
rubix-kubelet = { version = "=0.1.0", path = "../rubix-kubelet" }
rubix-pki = { version = "=0.1.0", path = "../rubix-pki" }
rubix-portainer = { version = "=0.1.0", path = "../rubix-portainer" }
rubix-proxy = { version = "=0.1.0", path = "../rubix-proxy" }
rubix-storage = { version = "=0.1.0", path = "../rubix-storage" }

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "=1.1.5", features = ["fs", "mount"] }

[dev-dependencies]
tempfile = "=3.27.0"
tokio = { version = "=1.53.1", features = ["test-util"] }

[[test]]
name = "suite"
path = "tests/suite.rs"
