[package]
name = "rubix-kube"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
rubix-config = { version = "=0.1.0", path = "../rubix-config" }
rubix-network = { version = "=0.1.0", path = "../rubix-network" }
serde_json = "=1.0.151"
rubix-platform = { version = "=0.1.0", path = "../rubix-platform" }
rubix-supervisor = { version = "=0.1.0", path = "../rubix-supervisor" }
tokio = { version = "=1.53.1", features = ["rt", "rt-multi-thread", "sync", "time", "macros", "signal"] }

rubix-apiserver = { version = "=0.1.0", path = "../rubix-apiserver" }
rubix-controller = { version = "=0.1.0", path = "../rubix-controller" }
rubix-datastore = { version = "=0.1.0", path = "../rubix-datastore" }
rubix-dns = { version = "=0.1.0", path = "../rubix-dns" }
rubix-pki = { version = "=0.1.0", path = "../rubix-pki" }
rubix-portainer = { version = "=0.1.0", path = "../rubix-portainer" }
rubix-proxy = { version = "=0.1.0", path = "../rubix-proxy" }
rubix-storage = { version = "=0.1.0", path = "../rubix-storage" }

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "=1.1.5", features = ["fs", "mount"] }

[dev-dependencies]
tempfile = "=3.27.0"
tokio = { version = "=1.53.1", features = ["test-util"] }

