//! Integration tests for recovery rehearsal qualification and Criterion 5 receipts (Issue #352 / E36.02).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use rubix_dev::recovery_rehearsal::{
    CRITERION_NUMBER, RECEIPT_FILENAME, REPORT_FILENAME, capture_recovery_qualification,
    verify_recovery_receipt,
};
use rubix_dev::release_qualification::receipt::CandidateReceipt;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

#[test]
fn test_recovery_rehearsal_capture_and_verify_programmatic() {
    let root = repo_root();
    let temp_dir = tempfile::tempdir().expect("create temp dir");
    let out_dir = temp_dir.path().join("rec_out");

    let (receipt_path, report_path) =
        capture_recovery_qualification(&out_dir, &root).expect("capture recovery qualification");

    assert!(receipt_path.is_file(), "receipt file must exist");
    assert!(report_path.is_file(), "report file must exist");
    assert_eq!(
        receipt_path.file_name().unwrap().to_str().unwrap(),
        RECEIPT_FILENAME
    );
    assert_eq!(
        report_path.file_name().unwrap().to_str().unwrap(),
        REPORT_FILENAME
    );

    // Verify report contents
    let report_content = fs::read_to_string(&report_path).expect("read report");
    let report_json: serde_json::Value =
        serde_json::from_str(&report_content).expect("parse report json");
    assert_eq!(report_json["criterion"], CRITERION_NUMBER);
    assert_eq!(report_json["assertions"].as_array().unwrap().len(), 7);

    // Verify receipt using verification function (file path)
    let receipt = verify_recovery_receipt(&receipt_path, &root).expect("verify receipt by file");
    assert_eq!(receipt.criterion, CRITERION_NUMBER);
    assert_eq!(receipt.assertions.len(), 7);
    for a in &receipt.assertions {
        assert!(a.passed, "assertion '{}' must pass", a.name);
    }

    // Verify receipt using directory path
    let receipt_dir =
        verify_recovery_receipt(&out_dir, &root).expect("verify receipt by directory");
    assert_eq!(receipt_dir.criterion, CRITERION_NUMBER);

    // Check required assertions are present
    let names: Vec<_> = receipt.assertions.iter().map(|a| a.name.as_str()).collect();
    assert!(names.contains(&"crash_restart_state_retention"));
    assert!(names.contains(&"bounded_escalation_and_cleanup"));
    assert!(names.contains(&"datastore_outage_blocking_r2"));
    assert!(names.contains(&"reboot_state_retention"));
    assert!(names.contains(&"wal_torn_write_fails_closed"));
    assert!(names.contains(&"startup_interruption_safe_reentry"));
    assert!(names.contains(&"ownership_cleanup_isolation"));

    // Check documented skips
    let skip_names: Vec<_> = receipt.skips.iter().map(|s| s.name.as_str()).collect();
    assert!(skip_names.contains(&"physical_host_reboot"));
}

#[test]
fn test_recovery_rehearsal_tamper_rejection() {
    let root = repo_root();
    let temp_dir = tempfile::tempdir().expect("create temp dir");
    let out_dir = temp_dir.path().join("rec_tamper");

    let (receipt_path, _) =
        capture_recovery_qualification(&out_dir, &root).expect("capture recovery qualification");

    let raw_bytes = fs::read(&receipt_path).expect("read receipt");
    let mut receipt: CandidateReceipt =
        serde_json::from_slice(&raw_bytes).expect("parse candidate receipt");

    // Invert one assertion's passed status without updating hash
    if let Some(first) = receipt.assertions.first_mut() {
        first.passed = false;
    }
    let tampered_bytes = serde_json::to_vec_pretty(&receipt).expect("serialize tampered receipt");
    let tampered_path = out_dir.join("tampered_receipt.json");
    fs::write(&tampered_path, tampered_bytes).expect("write tampered receipt");

    // Verification must fail closed on tampered receipt
    let verify_res = verify_recovery_receipt(&tampered_path, &root);
    assert!(
        verify_res.is_err(),
        "tampered receipt must fail verification"
    );
}

#[test]
fn test_recovery_rehearsal_cli_execution() {
    let root = repo_root();
    let temp_dir = tempfile::tempdir().expect("create temp dir");
    let out_dir = temp_dir.path().join("cli_rec");

    // Test capture CLI
    let capture_status = Command::new(env!("CARGO_BIN_EXE_rubix-recovery-rehearsal"))
        .arg("capture")
        .arg("--output")
        .arg(&out_dir)
        .current_dir(&root)
        .status()
        .expect("execute capture command");
    assert!(capture_status.success(), "capture command must succeed");

    let receipt_path = out_dir.join(RECEIPT_FILENAME);
    assert!(receipt_path.is_file(), "receipt must be generated by CLI");

    // Test verify CLI with file
    let verify_status = Command::new(env!("CARGO_BIN_EXE_rubix-recovery-rehearsal"))
        .arg("verify")
        .arg(&receipt_path)
        .current_dir(&root)
        .status()
        .expect("execute verify command");
    assert!(verify_status.success(), "verify command must succeed");

    // Test verify CLI with directory
    let verify_dir_status = Command::new(env!("CARGO_BIN_EXE_rubix-recovery-rehearsal"))
        .arg("verify")
        .arg(&out_dir)
        .current_dir(&root)
        .status()
        .expect("execute verify directory command");
    assert!(
        verify_dir_status.success(),
        "verify directory command must succeed"
    );

    // Test migration command fallback
    let migration_status = Command::new(env!("CARGO_BIN_EXE_rubix-recovery-rehearsal"))
        .arg("migration")
        .current_dir(&root)
        .status()
        .expect("execute migration command");
    assert!(
        migration_status.success(),
        "migration fallback must succeed"
    );
}
