[package]
name = "rubixctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
shlex = "=2.0.1"
rubix-config = { version = "=0.1.0", path = "../rubix-config" }
rubix-platform = { version = "=0.1.0", path = "../rubix-platform" }
rubix-supervisor = { version = "=0.1.0", path = "../rubix-supervisor" }
serde_json = "=1.0.151"
tempfile = "=3.27.0"
tokio = { version = "=1.53.1", features = ["rt", "macros", "sync", "time", "signal"] }

[dev-dependencies]
serde_json = "=1.0.151"
