[package]
name = "rubixctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tempfile = "=3.27.0"
rubix-platform = { version = "=0.1.0", path = "../rubix-platform" }

rubix-supervisor = { version = "=0.1.0", path = "../rubix-supervisor" }
tokio = { version = "=1.53.1", features = ["rt", "macros", "sync", "time", "signal"] }
rubix-assets = { version = "0.1.0", path = "../rubix-assets" }
sha2 = { version = "=0.11.0", default-features = false }

[target.'cfg(unix)'.dependencies]
rustix = { version = "=1.1.5", features = ["fs"] }

[dev-dependencies]
serde_json = "=1.0.151"
