use std::net::IpAddr;
use std::sync::Arc;

use rubix_apiserver::{ApiserverConfig, ApiserverService, KubernetesStorage};
use rubix_controller::{ControllerManagerConfig, ControllerManagerService};
use rubix_datastore::{DatastoreConfig, DatastoreEngine};
use rubix_pki::cluster::{ClusterPki, ClusterPkiConfig};
use serde_json::json;
use tempfile::TempDir;

fn setup_test_controller(dir: &TempDir) -> ControllerManagerService {
    let node_ip: IpAddr = "192.0.2.1".parse().unwrap();
    let pki_dir = dir.path().join("pki");
    std::fs::create_dir_all(&pki_dir).unwrap();
    let datastore_dir = dir.path().join("datastore");

    let pki_config = ClusterPkiConfig::new(pki_dir.clone(), "test-node".to_string(), node_ip);
    let pki = ClusterPki::new(pki_config);
    pki.reconcile().expect("PKI reconcile");

    let (engine, _) = DatastoreEngine::open(DatastoreConfig::new(datastore_dir)).unwrap();
    let storage = KubernetesStorage::new(engine.client(), "/registry");

    let apiserver_config = ApiserverConfig::default_for_pki(&pki_dir, node_ip);
    let apiserver_service = ApiserverService::new(apiserver_config, storage);

    let controller_config = ControllerManagerConfig::default_for_pki(&pki_dir, node_ip);
    let apiserver_arc = Arc::new(apiserver_service);

    ControllerManagerService::new(controller_config, apiserver_arc)
}

#[tokio::test]
async fn test_deployment_and_replicaset_reconciliation_and_scaling() {
    let temp = TempDir::new().unwrap();
    let controller_svc = setup_test_controller(&temp);
    controller_svc.start().await.unwrap();

    let client = controller_svc.client();
    let wm = controller_svc.workload_manager();
    let ns = "test-deploy-ns";

    client.create_namespace(ns).await.unwrap();

    // 1. Create a Deployment with 3 replicas
    let deployment = json!({
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
            "name": "web-deploy",
            "namespace": ns
        },
        "spec": {
            "replicas": 3,
            "selector": {
                "matchLabels": { "app": "web" }
            },
            "template": {
                "metadata": {
                    "labels": { "app": "web" }
                },
                "spec": {
                    "containers": [{
                        "name": "nginx",
                        "image": "nginx:1.27"
                    }]
                }
            }
        }
    });

    client.create_deployment(ns, deployment).await.unwrap();

    // First reconciliation pass: Deployment -> ReplicaSet
    let summary1 = wm.reconcile_namespace(ns).await.unwrap();
    assert_eq!(summary1.deployments_reconciled, 1);
    assert_eq!(summary1.replicasets_reconciled, 1);

    // Verify child ReplicaSet exists and has owner reference pointing to Deployment
    let rs = client.get_replicaset(ns, "web-deploy-rs").await.unwrap();
    assert_eq!(rs["spec"]["replicas"], 3);
    let owner_refs = rs["metadata"]["ownerReferences"].as_array().unwrap();
    assert_eq!(owner_refs.len(), 1);
    assert_eq!(owner_refs[0]["kind"], "Deployment");
    assert_eq!(owner_refs[0]["name"], "web-deploy");

    // Second reconciliation pass: ReplicaSet -> Pods
    let summary2 = wm.reconcile_namespace(ns).await.unwrap();
    assert_eq!(summary2.deployments_reconciled, 1);
    assert_eq!(summary2.replicasets_reconciled, 1);

    let pod_list = client.list_pods(ns).await.unwrap();
    let pods = pod_list["items"].as_array().unwrap();
    assert_eq!(pods.len(), 3, "expected 3 pods generated by replicaset");

    for pod in pods {
        assert_eq!(
            pod["status"]["phase"], "Pending",
            "Pods must default to Pending phase without requiring a scheduler"
        );
        let pod_owners = pod["metadata"]["ownerReferences"].as_array().unwrap();
        assert_eq!(pod_owners[0]["kind"], "ReplicaSet");
        assert_eq!(pod_owners[0]["name"], "web-deploy-rs");
    }

    // 2. Scale Deployment up to 4
    let mut updated_dep = client.get_deployment(ns, "web-deploy").await.unwrap();
    updated_dep["spec"]["replicas"] = json!(4);
    client
        .update_deployment(ns, "web-deploy", updated_dep)
        .await
        .unwrap();

    let _ = wm.reconcile_namespace(ns).await.unwrap();
    let pod_list_scaled_up = client.list_pods(ns).await.unwrap();
    assert_eq!(pod_list_scaled_up["items"].as_array().unwrap().len(), 4);

    // 3. Scale Deployment down to 1
    let mut updated_dep_down = client.get_deployment(ns, "web-deploy").await.unwrap();
    updated_dep_down["spec"]["replicas"] = json!(1);
    client
        .update_deployment(ns, "web-deploy", updated_dep_down)
        .await
        .unwrap();

    let _ = wm.reconcile_namespace(ns).await.unwrap();
    let pod_list_scaled_down = client.list_pods(ns).await.unwrap();
    assert_eq!(pod_list_scaled_down["items"].as_array().unwrap().len(), 1);
}

#[tokio::test]
async fn test_statefulset_ordinal_pod_reconciliation() {
    let temp = TempDir::new().unwrap();
    let controller_svc = setup_test_controller(&temp);
    controller_svc.start().await.unwrap();

    let client = controller_svc.client();
    let wm = controller_svc.workload_manager();
    let ns = "test-ss-ns";

    client.create_namespace(ns).await.unwrap();

    let statefulset = json!({
        "apiVersion": "apps/v1",
        "kind": "StatefulSet",
        "metadata": {
            "name": "redis",
            "namespace": ns
        },
        "spec": {
            "replicas": 3,
            "template": {
                "metadata": {
                    "labels": { "app": "redis" }
                },
                "spec": {
                    "containers": [{ "name": "redis", "image": "redis:7" }]
                }
            }
        }
    });

    client.create_statefulset(ns, statefulset).await.unwrap();

    let _ = wm.reconcile_namespace(ns).await.unwrap();

    // Verify ordinal pods: redis-0, redis-1, redis-2
    for idx in 0..3 {
        let pod_name = format!("redis-{idx}");
        let pod = client
            .get_pod(ns, &pod_name)
            .await
            .expect("ordinal pod exists");
        assert_eq!(
            pod["metadata"]["labels"]["statefulset.kubernetes.io/pod-name"],
            pod_name
        );
        assert_eq!(
            pod["metadata"]["labels"]["apps.kubernetes.io/pod-index"],
            idx.to_string()
        );
        assert_eq!(pod["status"]["phase"], "Pending");
        let owners = pod["metadata"]["ownerReferences"].as_array().unwrap();
        assert_eq!(owners[0]["kind"], "StatefulSet");
        assert_eq!(owners[0]["name"], "redis");
    }

    // Scale down to 1: redis-1 and redis-2 should be removed
    let mut ss_scale = client.get_statefulset(ns, "redis").await.unwrap();
    ss_scale["spec"]["replicas"] = json!(1);
    client
        .update_statefulset(ns, "redis", ss_scale)
        .await
        .unwrap();

    let _ = wm.reconcile_namespace(ns).await.unwrap();

    assert!(client.get_pod(ns, "redis-0").await.is_ok());
    assert!(client.get_pod(ns, "redis-1").await.is_err());
    assert!(client.get_pod(ns, "redis-2").await.is_err());
}

#[tokio::test]
async fn test_daemonset_node_pod_reconciliation() {
    let temp = TempDir::new().unwrap();
    let controller_svc = setup_test_controller(&temp);
    controller_svc.start().await.unwrap();

    let client = controller_svc.client();
    let wm = controller_svc.workload_manager();
    let ns = "test-ds-ns";

    client.create_namespace(ns).await.unwrap();

    let daemonset = json!({
        "apiVersion": "apps/v1",
        "kind": "DaemonSet",
        "metadata": {
            "name": "node-exporter",
            "namespace": ns
        },
        "spec": {
            "template": {
                "metadata": {
                    "labels": { "app": "node-exporter" }
                },
                "spec": {
                    "containers": [{ "name": "exporter", "image": "prom/node-exporter" }]
                }
            }
        }
    });

    client.create_daemonset(ns, daemonset).await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();

    let pod = client
        .get_pod(ns, "node-exporter-node")
        .await
        .expect("daemon pod exists");
    assert_eq!(pod["status"]["phase"], "Pending");
    let owners = pod["metadata"]["ownerReferences"].as_array().unwrap();
    assert_eq!(owners[0]["kind"], "DaemonSet");
    assert_eq!(owners[0]["name"], "node-exporter");
}

#[tokio::test]
async fn test_job_and_cronjob_reconciliation() {
    let temp = TempDir::new().unwrap();
    let controller_svc = setup_test_controller(&temp);
    controller_svc.start().await.unwrap();

    let client = controller_svc.client();
    let wm = controller_svc.workload_manager();
    let ns = "test-batch-ns";

    client.create_namespace(ns).await.unwrap();

    // 1. Reconcile standalone Job with parallelism = 2
    let job = json!({
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {
            "name": "pi-job",
            "namespace": ns
        },
        "spec": {
            "parallelism": 2,
            "template": {
                "spec": {
                    "containers": [{ "name": "pi", "image": "perl" }]
                }
            }
        }
    });

    client.create_job(ns, job).await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();

    let pod0 = client
        .get_pod(ns, "pi-job-0")
        .await
        .expect("job pod 0 exists");
    let pod1 = client
        .get_pod(ns, "pi-job-1")
        .await
        .expect("job pod 1 exists");
    assert_eq!(pod0["metadata"]["labels"]["job-name"], "pi-job");
    assert_eq!(pod1["metadata"]["labels"]["job-name"], "pi-job");

    // 2. Reconcile CronJob
    let cronjob = json!({
        "apiVersion": "batch/v1",
        "kind": "CronJob",
        "metadata": {
            "name": "backup-cron",
            "namespace": ns
        },
        "spec": {
            "schedule": "*/5 * * * *",
            "jobTemplate": {
                "spec": {
                    "template": {
                        "spec": {
                            "containers": [{ "name": "backup", "image": "busybox" }]
                        }
                    }
                }
            }
        }
    });

    client.create_cronjob(ns, cronjob).await.unwrap();

    // Pass 1: CronJob -> child Job
    let _ = wm.reconcile_namespace(ns).await.unwrap();
    let child_job = client
        .get_job(ns, "backup-cron-scheduled")
        .await
        .expect("scheduled job exists");
    let cj_owners = child_job["metadata"]["ownerReferences"].as_array().unwrap();
    assert_eq!(cj_owners[0]["kind"], "CronJob");
    assert_eq!(cj_owners[0]["name"], "backup-cron");

    // Pass 2: Scheduled Job -> child Pod
    let _ = wm.reconcile_namespace(ns).await.unwrap();
    let cron_pod = client
        .get_pod(ns, "backup-cron-scheduled-0")
        .await
        .expect("cron job child pod exists");
    assert_eq!(cron_pod["status"]["phase"], "Pending");
}

#[tokio::test]
async fn test_garbage_collection_cascading_deletions() {
    let temp = TempDir::new().unwrap();
    let controller_svc = setup_test_controller(&temp);
    controller_svc.start().await.unwrap();

    let client = controller_svc.client();
    let wm = controller_svc.workload_manager();
    let ns = "test-gc-ns";

    client.create_namespace(ns).await.unwrap();

    // 1. Create Deployment, reconcile to produce ReplicaSet and Pods
    let deployment = json!({
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": { "name": "doomed-deploy", "namespace": ns },
        "spec": {
            "replicas": 2,
            "template": { "spec": { "containers": [{ "name": "app", "image": "nginx" }] } }
        }
    });
    client.create_deployment(ns, deployment).await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();

    assert!(client.get_replicaset(ns, "doomed-deploy-rs").await.is_ok());
    assert!(client.get_pod(ns, "doomed-deploy-rs-0").await.is_ok());
    assert!(client.get_pod(ns, "doomed-deploy-rs-1").await.is_ok());

    // 2. Delete parent Deployment and run reconciliation (which triggers GarbageCollector)
    client.delete_deployment(ns, "doomed-deploy").await.unwrap();
    let summary = wm.reconcile_namespace(ns).await.unwrap();

    assert!(
        summary.garbage_collected >= 3,
        "GC should have collected 1 ReplicaSet and 2 Pods"
    );
    assert!(client.get_replicaset(ns, "doomed-deploy-rs").await.is_err());
    assert!(client.get_pod(ns, "doomed-deploy-rs-0").await.is_err());
    assert!(client.get_pod(ns, "doomed-deploy-rs-1").await.is_err());

    // 3. Create and cascade delete StatefulSet
    let ss = json!({
        "apiVersion": "apps/v1",
        "kind": "StatefulSet",
        "metadata": { "name": "doomed-ss", "namespace": ns },
        "spec": {
            "replicas": 2,
            "template": { "spec": { "containers": [{ "name": "app", "image": "redis" }] } }
        }
    });
    client.create_statefulset(ns, ss).await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();
    assert!(client.get_pod(ns, "doomed-ss-0").await.is_ok());
    assert!(client.get_pod(ns, "doomed-ss-1").await.is_ok());

    client.delete_statefulset(ns, "doomed-ss").await.unwrap();
    let statefulset_gc = wm.reconcile_namespace(ns).await.unwrap();
    assert!(statefulset_gc.garbage_collected >= 2);
    assert!(client.get_pod(ns, "doomed-ss-0").await.is_err());
    assert!(client.get_pod(ns, "doomed-ss-1").await.is_err());

    // 4. Create and cascade delete DaemonSet
    let ds = json!({
        "apiVersion": "apps/v1",
        "kind": "DaemonSet",
        "metadata": { "name": "doomed-ds", "namespace": ns },
        "spec": {
            "template": { "spec": { "containers": [{ "name": "app", "image": "exporter" }] } }
        }
    });
    client.create_daemonset(ns, ds).await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();
    assert!(client.get_pod(ns, "doomed-ds-node").await.is_ok());

    client.delete_daemonset(ns, "doomed-ds").await.unwrap();
    let daemonset_gc = wm.reconcile_namespace(ns).await.unwrap();
    assert!(daemonset_gc.garbage_collected >= 1);
    assert!(client.get_pod(ns, "doomed-ds-node").await.is_err());

    // 5. Create and cascade delete CronJob (CronJob -> Job -> Pod)
    let cj = json!({
        "apiVersion": "batch/v1",
        "kind": "CronJob",
        "metadata": { "name": "doomed-cj", "namespace": ns },
        "spec": {
            "schedule": "* * * * *",
            "jobTemplate": {
                "spec": { "template": { "spec": { "containers": [{ "name": "c", "image": "busybox" }] } } }
            }
        }
    });
    client.create_cronjob(ns, cj).await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();
    assert!(client.get_job(ns, "doomed-cj-scheduled").await.is_ok());
    assert!(client.get_pod(ns, "doomed-cj-scheduled-0").await.is_ok());

    client.delete_cronjob(ns, "doomed-cj").await.unwrap();
    let cronjob_gc = wm.reconcile_namespace(ns).await.unwrap();
    assert!(cronjob_gc.garbage_collected >= 2);
    assert!(client.get_job(ns, "doomed-cj-scheduled").await.is_err());
    assert!(client.get_pod(ns, "doomed-cj-scheduled-0").await.is_err());
}

#[tokio::test]
async fn test_idempotence_and_restart_convergence() {
    let temp = TempDir::new().unwrap();
    let controller_svc = setup_test_controller(&temp);
    controller_svc.start().await.unwrap();

    let client = controller_svc.client();
    let wm1 = controller_svc.workload_manager();
    let ns = "test-idempotence-ns";

    client.create_namespace(ns).await.unwrap();

    // Create a Deployment with 2 replicas
    let deployment = json!({
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": { "name": "stable-deploy", "namespace": ns },
        "spec": {
            "replicas": 2,
            "template": { "spec": { "containers": [{ "name": "app", "image": "nginx" }] } }
        }
    });
    client.create_deployment(ns, deployment).await.unwrap();

    // Reconcile multiple times
    for _ in 0..5 {
        let _ = wm1.reconcile_namespace(ns).await.unwrap();
    }

    let pods = client.list_pods(ns).await.unwrap();
    assert_eq!(
        pods["items"].as_array().unwrap().len(),
        2,
        "repeated reconciliation loops must not produce duplicate pods"
    );

    // Simulate controller restart: fresh WorkloadManager
    let wm2 = controller_svc.workload_manager();
    for _ in 0..3 {
        let _ = wm2.reconcile_namespace(ns).await.unwrap();
    }

    let pods_after_restart = client.list_pods(ns).await.unwrap();
    assert_eq!(
        pods_after_restart["items"].as_array().unwrap().len(),
        2,
        "controller restart must converge without creating duplicate resources"
    );
}

#[tokio::test]
async fn test_replicaset_and_job_gap_recovery() {
    let temp = TempDir::new().unwrap();
    let controller_svc = setup_test_controller(&temp);
    controller_svc.start().await.unwrap();

    let client = controller_svc.client();
    let wm = controller_svc.workload_manager();
    let ns = "test-gap-ns";

    client.create_namespace(ns).await.unwrap();

    // 1. ReplicaSet gap recovery: create 3 replicas (gap-rs-0, gap-rs-1, gap-rs-2)
    let rs = json!({
        "apiVersion": "apps/v1",
        "kind": "ReplicaSet",
        "metadata": { "name": "gap-rs", "namespace": ns },
        "spec": {
            "replicas": 3,
            "template": { "spec": { "containers": [{ "name": "app", "image": "nginx" }] } }
        }
    });
    client.create_replicaset(ns, rs).await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();

    let pods = client.list_pods(ns).await.unwrap();
    assert_eq!(pods["items"].as_array().unwrap().len(), 3);

    // Delete middle pod gap-rs-1 to create an index gap (gap-rs-0, gap-rs-2 remain)
    client.delete_pod(ns, "gap-rs-1").await.unwrap();
    let pods_after_del = client.list_pods(ns).await.unwrap();
    assert_eq!(pods_after_del["items"].as_array().unwrap().len(), 2);

    // Reconcile: must recover and fill the gap back to 3 replicas
    let _ = wm.reconcile_namespace(ns).await.unwrap();
    let pods_recovered = client.list_pods(ns).await.unwrap();
    assert_eq!(
        pods_recovered["items"].as_array().unwrap().len(),
        3,
        "ReplicaSet scale-up must recover when pod indices have gaps"
    );

    // 2. Job gap recovery: create Job with parallelism 3
    let job = json!({
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": { "name": "gap-job", "namespace": ns },
        "spec": {
            "parallelism": 3,
            "template": { "spec": { "containers": [{ "name": "job", "image": "busybox" }] } }
        }
    });
    client.create_job(ns, job).await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();

    // Delete gap-job-1
    client.delete_pod(ns, "gap-job-1").await.unwrap();
    let _ = wm.reconcile_namespace(ns).await.unwrap();

    let all_job_pods: Vec<_> = client.list_pods(ns).await.unwrap()["items"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|p| {
            p["metadata"]["name"]
                .as_str()
                .unwrap_or("")
                .starts_with("gap-job-")
        })
        .cloned()
        .collect();
    assert_eq!(
        all_job_pods.len(),
        3,
        "Job scale-up must recover when pod indices have gaps"
    );
}
