//! Publication checksum manifests, source provenance, license inventories and
//! release layout verification for candidate artifacts (E27.03).
//!
//! Every output is deterministic (sorted, no timestamps). Pinned inputs make candidate
//! assembly repeatable; this module does not claim bit-for-bit reproducibility of the
//! binaries themselves, see [`Reproducibility`].

use crate::Result;
use rubix_assets::{
    AssetId, DeclaredInventory, NodeArchiveArtifact, ReleasePackageManifest, ReleasePackager,
    catalog,
};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// Name of the publication checksum manifest written next to the artifacts.
pub const CHECKSUM_FILE: &str = "SHA256SUMS";
/// Files generated by this module that are never listed in the checksum manifest.
const GENERATED_FILES: [&str; 4] = [
    CHECKSUM_FILE,
    "provenance.json",
    "licenses.json",
    "release-manifest.json",
];

fn is_sha256_hex(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))
}

/// Failure verifying artifacts against a checksum manifest.
#[derive(Debug, PartialEq, Eq)]
pub enum ChecksumError {
    Malformed(String),
    Missing(String),
    Mismatch {
        file: String,
        expected: String,
        observed: String,
    },
    Unlisted(String),
}

impl std::fmt::Display for ChecksumError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Malformed(line) => write!(f, "malformed checksum line: {line:?}"),
            Self::Missing(file) => write!(f, "listed artifact is missing: {file}"),
            Self::Mismatch {
                file,
                expected,
                observed,
            } => write!(f, "{file}: expected sha256 {expected}, observed {observed}"),
            Self::Unlisted(file) => write!(f, "artifact is not in the checksum manifest: {file}"),
        }
    }
}

impl std::error::Error for ChecksumError {}

/// `sha256sum`-compatible manifest mapping artifact file names to digests.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ChecksumManifest {
    entries: BTreeMap<String, String>,
}

impl ChecksumManifest {
    /// Digest every regular artifact in `dir`, excluding generated publication files.
    pub fn generate(dir: &Path) -> Result<Self> {
        let mut entries = BTreeMap::new();
        for artifact in artifact_files(dir)? {
            let bytes = fs::read(dir.join(&artifact))?;
            entries.insert(artifact, ReleasePackager::sha256_hex(&bytes));
        }
        Ok(Self { entries })
    }

    /// Parse `sha256sum` text (`<hex>  <name>`), rejecting malformed or duplicate lines.
    pub fn parse(text: &str) -> std::result::Result<Self, ChecksumError> {
        let mut entries = BTreeMap::new();
        for line in text.lines().filter(|line| !line.is_empty()) {
            let (digest, name) = line
                .split_once("  ")
                .filter(|(digest, name)| {
                    is_sha256_hex(digest)
                        && !name.is_empty()
                        && !name.contains(['/', '\\'])
                        && *name != ".."
                })
                .ok_or_else(|| ChecksumError::Malformed(line.to_string()))?;
            if entries
                .insert(name.to_string(), digest.to_string())
                .is_some()
            {
                return Err(ChecksumError::Malformed(format!("duplicate entry: {name}")));
            }
        }
        Ok(Self { entries })
    }

    /// Render in sorted `sha256sum` format.
    pub fn render(&self) -> String {
        let mut out = String::new();
        for (name, digest) in &self.entries {
            let _ = writeln!(out, "{digest}  {name}");
        }
        out
    }

    pub fn entries(&self) -> &BTreeMap<String, String> {
        &self.entries
    }

    /// Detect tampering, missing files and unlisted files in `dir`.
    pub fn verify(&self, dir: &Path) -> Result<()> {
        for (name, expected) in &self.entries {
            let path = dir.join(name);
            if !path.is_file() {
                return Err(ChecksumError::Missing(name.clone()).into());
            }
            let observed = ReleasePackager::sha256_hex(&fs::read(&path)?);
            if &observed != expected {
                return Err(ChecksumError::Mismatch {
                    file: name.clone(),
                    expected: expected.clone(),
                    observed,
                }
                .into());
            }
        }
        for artifact in artifact_files(dir)? {
            if !self.entries.contains_key(&artifact) {
                return Err(ChecksumError::Unlisted(artifact).into());
            }
        }
        Ok(())
    }
}

fn artifact_files(dir: &Path) -> Result<Vec<String>> {
    let mut names = Vec::new();
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        if !entry.file_type()?.is_file() {
            continue;
        }
        let name = entry
            .file_name()
            .into_string()
            .map_err(|name| format!("non-UTF-8 artifact name: {}", name.to_string_lossy()))?;
        if !GENERATED_FILES.contains(&name.as_str()) {
            names.push(name);
        }
    }
    names.sort();
    Ok(names)
}

/// One pinned generation input from `tools/upstream/inputs.json`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct GeneratedInput {
    pub id: String,
    pub path: String,
    pub url: String,
    pub sha256: String,
    pub bytes: u64,
}

/// One upstream source repository pinned by `docs/architecture/upstream-inputs.json`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct UpstreamSource {
    pub repository: String,
    pub tag: String,
    pub commit: String,
    #[serde(default)]
    pub role: Option<String>,
}

/// Retained non-Rust component shipped or referenced by a candidate.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RetainedComponent {
    pub id: String,
    pub kind: String,
    pub reference: String,
}

/// Exact artifact digest the inventories are tied to.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ArtifactDigest {
    pub filename: String,
    pub sha256: String,
}

/// Statement of what assembly repeatability is and is not claimed.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Reproducibility {
    pub inputs_pinned: bool,
    pub bit_for_bit_claimed: bool,
    pub remaining_nondeterminism: Vec<String>,
}

impl Reproducibility {
    fn current() -> Self {
        Self {
            inputs_pinned: true,
            bit_for_bit_claimed: false,
            remaining_nondeterminism: vec![
                "Rust binaries are not verified bit-for-bit reproducible across hosts or toolchain \
                 paths"
                    .to_string(),
                "retained upstream executables and images are consumed as pinned digests, not \
                 rebuilt"
                    .to_string(),
                "archive container metadata (mtime, ordering) is not independently re-verified"
                    .to_string(),
            ],
        }
    }
}

/// Source provenance record for a candidate.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceProvenance {
    pub schema_version: u32,
    pub version: String,
    pub baseline: String,
    pub upstream_sources: Vec<UpstreamSource>,
    pub generated_inputs: Vec<GeneratedInput>,
    pub retained_components: Vec<RetainedComponent>,
    pub artifacts: Vec<ArtifactDigest>,
    pub reproducibility: Reproducibility,
}

#[derive(Deserialize)]
struct GeneratorInputs {
    sources: Vec<GeneratedInput>,
}

#[derive(Deserialize)]
struct InventoryDocument {
    baseline: String,
    sources: Vec<UpstreamSource>,
}

/// Build the provenance record from pinned inventories and the checksum manifest.
pub fn generate_source_provenance(
    generator_inputs_json: &str,
    upstream_inventory_json: &str,
    version: &str,
    checksums: &ChecksumManifest,
) -> Result<SourceProvenance> {
    let generator: GeneratorInputs = serde_json::from_str(generator_inputs_json)?;
    let inventory: InventoryDocument = serde_json::from_str(upstream_inventory_json)?;
    if generator.sources.is_empty() || inventory.sources.is_empty() {
        return Err("provenance inventories must list sources".into());
    }
    for input in &generator.sources {
        if !is_sha256_hex(&input.sha256) {
            return Err(format!("generated input {} has an invalid sha256", input.id).into());
        }
    }
    let retained_components = catalog()
        .iter()
        .map(|entry| RetainedComponent {
            id: asset_id_name(entry.id),
            kind: format!("{:?}", entry.kind).to_ascii_lowercase(),
            reference: entry.reference.to_string(),
        })
        .collect();
    Ok(SourceProvenance {
        schema_version: 1,
        version: version.to_string(),
        baseline: inventory.baseline,
        upstream_sources: inventory.sources,
        generated_inputs: generator.sources,
        retained_components,
        artifacts: checksums
            .entries()
            .iter()
            .map(|(filename, sha256)| ArtifactDigest {
                filename: filename.clone(),
                sha256: sha256.clone(),
            })
            .collect(),
        reproducibility: Reproducibility::current(),
    })
}

fn asset_id_name(id: AssetId) -> String {
    format!("{id:?}")
}

/// License entry for a Rust dependency or a retained component.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LicenseEntry {
    pub name: String,
    pub version: String,
    /// SPDX expression, or `unrecorded` when the source does not declare one.
    pub license: String,
}

/// License inventory attached to a candidate.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LicenseInventory {
    pub schema_version: u32,
    pub rust_dependencies: Vec<LicenseEntry>,
    /// Retained non-Rust components; licenses are not resolved by this tool.
    pub retained_components: Vec<LicenseEntry>,
}

#[derive(Deserialize)]
struct CargoMetadata {
    packages: Vec<CargoPackage>,
}

#[derive(Deserialize)]
struct CargoPackage {
    name: String,
    version: String,
    license: Option<String>,
}

/// Build the license inventory from `cargo metadata --locked --format-version 1` output.
pub fn generate_license_inventory(cargo_metadata_json: &str) -> Result<LicenseInventory> {
    let metadata: CargoMetadata = serde_json::from_str(cargo_metadata_json)?;
    let mut rust_dependencies: Vec<LicenseEntry> = metadata
        .packages
        .into_iter()
        .map(|package| LicenseEntry {
            name: package.name,
            version: package.version,
            license: package.license.unwrap_or_else(|| "unrecorded".to_string()),
        })
        .collect();
    rust_dependencies.sort_by(|a, b| (&a.name, &a.version).cmp(&(&b.name, &b.version)));
    let retained_components = catalog()
        .iter()
        .map(|entry| LicenseEntry {
            name: asset_id_name(entry.id),
            version: entry.reference.to_string(),
            license: "unrecorded".to_string(),
        })
        .collect();
    Ok(LicenseInventory {
        schema_version: 1,
        rust_dependencies,
        retained_components,
    })
}

/// Build draft file descriptors using real digests. This cannot infer bundled asset
/// inventories or OCI indices and does not produce a qualified release manifest.
pub fn generate_manifest(
    dist_dir: &Path,
    version: &str,
    node_prefix: &str,
    management_prefix: &str,
) -> Result<ReleasePackageManifest> {
    use rubix_assets::{ArtifactNaming, ManagementArtifact};
    let mut node_archives = Vec::new();
    let mut management_binaries = Vec::new();
    for filename in artifact_files(dist_dir)? {
        let content = fs::read(dist_dir.join(&filename))?;
        let sha256 = ReleasePackager::sha256_hex(&content);
        let size_bytes = content.len() as u64;
        if let Ok(parsed) = ArtifactNaming::parse_node_archive(&filename)
            && parsed.prefix == node_prefix
            && parsed.version == version
        {
            {
                node_archives.push(NodeArchiveArtifact {
                    cell: parsed.variant.cell,
                    filename: filename.clone(),
                    architecture: match parsed.variant.architecture {
                        rubix_assets::Architecture::Amd64 => "amd64",
                        rubix_assets::Architecture::Arm64 => "arm64",
                        rubix_assets::Architecture::ArmV7 => "arm",
                        rubix_assets::Architecture::Riscv64 => "riscv64",
                    }
                    .to_string(),
                    libc: format!("{:?}", parsed.variant.libc).to_ascii_lowercase(),
                    variant: format!("{:?}", parsed.variant.variant).to_ascii_lowercase(),
                    size_bytes,
                    sha256,
                    bundled_assets: Vec::new(),
                });
                continue;
            }
        }
        if let Ok(parsed) = ArtifactNaming::parse_management_binary(&filename)
            && parsed.prefix == management_prefix
        {
            management_binaries.push(ManagementArtifact {
                os: parsed.target.os.to_string(),
                architecture: parsed.target.architecture.to_string(),
                filename,
                size_bytes,
                sha256,
            });
        }
    }
    Ok(ReleasePackageManifest {
        schema_version: 1,
        product_name: node_prefix.to_string(),
        version: version.to_string(),
        node_archives,
        management_binaries,
        oci_images: Vec::new(),
        excluded_targets: vec![
            "Windows binaries (native win32/win64 excluded per E01; WSL2 uses Linux userspace)"
                .to_string(),
        ],
    })
}

/// Verify prepared manifest completeness and actual file digests/sizes. OCI
/// descriptors are validated as metadata; this does not fetch registry content.
pub fn verify_publication_artifacts(
    dist_dir: &Path,
    manifest: &ReleasePackageManifest,
    checksums: &ChecksumManifest,
    node_prefix: &str,
    management_prefix: &str,
) -> Result<()> {
    checksums.verify(dist_dir)?;
    ReleasePackager::verify_release_manifest(
        manifest,
        node_prefix,
        management_prefix,
        &manifest.version,
    )?;
    for binary in &manifest.management_binaries {
        match checksums.entries().get(&binary.filename) {
            Some(digest) if *digest == binary.sha256 => {},
            _ => {
                return Err(format!(
                    "manifest digest for {} disagrees with the checksum manifest",
                    binary.filename
                )
                .into());
            },
        }
        let observed_size = fs::metadata(dist_dir.join(&binary.filename))?.len();
        if observed_size != binary.size_bytes {
            return Err(format!(
                "manifest size for {} is {}, observed {}",
                binary.filename, binary.size_bytes, observed_size
            )
            .into());
        }
    }
    for archive in &manifest.node_archives {
        match checksums.entries().get(&archive.filename) {
            Some(digest) if *digest == archive.sha256 => {},
            _ => {
                return Err(format!(
                    "manifest digest for {} disagrees with the checksum manifest",
                    archive.filename
                )
                .into());
            },
        }
        let bytes = fs::read(dist_dir.join(&archive.filename))?;
        if bytes.len() as u64 != archive.size_bytes {
            return Err(
                format!("manifest size for {} disagrees with file", archive.filename).into(),
            );
        }
    }
    Ok(())
}

/// Verify a prepared publication's files and materialize dependency assets against
/// each supplied inventory. This does not run or qualify a node installation.
pub fn verify_publication(
    dist_dir: &Path,
    manifest: &ReleasePackageManifest,
    checksums: &ChecksumManifest,
    node_prefix: &str,
    management_prefix: &str,
    inventory_for: &dyn Fn(&NodeArchiveArtifact) -> Result<DeclaredInventory>,
) -> Result<()> {
    verify_publication_artifacts(
        dist_dir,
        manifest,
        checksums,
        node_prefix,
        management_prefix,
    )?;
    for archive in &manifest.node_archives {
        let bytes = fs::read(dist_dir.join(&archive.filename))?;
        let root = tempfile::tempdir()?;
        ReleasePackager::smoke_check_node_archive_layout(
            inventory_for(archive)?,
            root.path(),
            std::io::Cursor::new(bytes),
        )?;
    }
    Ok(())
}
