[alias]
lint = "clippy --locked --workspace --all-targets --all-features -- -D warnings"
fmt-check = "fmt --all -- --check"
test-all = "test --workspace --all-targets --all-features"
doc-all = "doc --workspace --all-features --no-deps"

[net]
git-fetch-with-cli = true
retry = 10
